name: Auto VTag

on:
  push:
    branches:
      - master
      - feature/ci

jobs:
  auto-vtag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find csproj file
        id: find_csproj
        run: |
          FILE=$(find . -name "*.csproj" | head -n 1)
          echo "::set-output name=FILE::$FILE"

      - name: Get version from csproj
        id: get_version
        run: |
          VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" ${{ steps.find_csproj.outputs.FILE }})
          echo "::set-output name=VERSION::$VERSION"

      - name: Check if tag exists
        id: check_tag
        run: |
          TAG_EXISTS=$(git tag -l "v${{ steps.get_version.outputs.VERSION }}")
          echo "::set-output name=TAG_EXISTS::$TAG_EXISTS"

      - name: Create tag
        if: steps.check_tag.outputs.TAG_EXISTS == ''
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag "v${{ steps.get_version.outputs.VERSION }}"
          git push origin "v${{ steps.get_version.outputs.VERSION }}"

