name: .NET Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Setup SteamCMD
      uses: CyberAndrii/setup-steamcmd@v1.2.0
      
    - name: Update app
      run: steamcmd +login ${{ secrets.STEAMLOGIN }} +app_update 2519830 validate +quit
      
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Restore the application
      run: msbuild /t:Restore /p:Configuration=RELEASE

    - name: Create the app package
      run: msbuild /p:Configuration=RELEASE

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: EsnyaResoniteModTemplate.dll
        path: ResoniteMetricsCounter/bin/Release/net472/EsnyaResoniteModTemplate.dll
