name: .NET Build

on:
  push:
    branches: [ "master" ]
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Setup SteamCMD
      uses: CyberAndrii/setup-steamcmd@v1.2.0
      
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Update app
      run: steamcmd +force_install_dir D:/a/EsnyaResoniteModTemplate/EsnyaResoniteModTemplate/Resonite +login ${{ secrets.STEAMLOGIN }} +app_update 2519830 validate +quit

    - name: Install ResoniteModLoader
      uses: suisei-cn/actions-download-file@v1
      with:
        url: https://github.com/resonite-modding-group/ResoniteModLoader/releases/latest/download/ResoniteModLoader.dll
        target: D:/a/EsnyaResoniteModTemplate/EsnyaResoniteModTemplate/Resonite/Libraries/
        
    - name: Install Harmony
      uses: suisei-cn/actions-download-file@v1
      with:
        url: https://github.com/resonite-modding-group/ResoniteModLoader/releases/latest/download/0Harmony.dll
        target: D:/a/EsnyaResoniteModTemplate/EsnyaResoniteModTemplate/Resonite/rml_libs/

    - name: Cache app
      uses: actions/cache@v4
      with:
        path: D:/a/EsnyaResoniteModTemplate/EsnyaResoniteModTemplate/Resonite/
        key: app-runtime

    - name: Restore the application
      run: msbuild /t:Restore /p:Configuration=RELEASE

    - name: Create the app package
      run: msbuild /p:Configuration=RELEASE

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: EsnyaResoniteModTemplate.dll
        path: EsnyaResoniteModTemplate/bin/Release/net472/EsnyaResoniteModTemplate.dll

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        body: |
          [Compare changes](https://github.com/${{ github.repository }}/compare/${{ github.event.before }}...${{ github.sha }})

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: EsnyaResoniteModTemplate/bin/Release/net472/EsnyaResoniteModTemplate.dll
        asset_name: EsnyaResoniteModTemplate.dll
        asset_content_type: application/octet-stream
