name: .NET Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Setup SteamCMD
      uses: CyberAndrii/setup-steamcmd@v1.2.0
      
    - name: Update app
      run: steamcmd +force_install_dir D:\a\EsnyaResoniteModTemplate\Resonite +login ${{ secrets.STEAMLOGIN }} +app_update 2519830 validate +quit

    - name: Install ResoniteModLoader
      uses: suisei-cn/actions-download-file@v1
      with:
        url: https://github.com/resonite-modding-group/ResoniteModLoader/releases/latest/download/ResoniteModLoader.dll
        target: D:/a/EsnyaResoniteModTemplate/Resonite/Libraries/
        
    - name: Install Harmony
      uses: suisei-cn/actions-download-file@v1
      with:
        url: https://github.com/resonite-modding-group/ResoniteModLoader/releases/latest/download/0Harmony.dll
        target: D:/a/EsnyaResoniteModTemplate/Resonite/rml_libs/

    - name: Cache app
      uses: actions/cache@v4
      with:
        path: D:/a/EsnyaResoniteModTemplate/Resonite/
        key: app

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Restore the application
      run: msbuild /t:Restore /p:Configuration=RELEASE /p:ResonitePath=D:/a/EsnyaResoniteModTemplate/Resonite/

    - name: Create the app package
      run: msbuild /p:Configuration=RELEASE

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: EsnyaResoniteModTemplate.dll
        path: ResoniteMetricsCounter/bin/Release/net472/EsnyaResoniteModTemplate.dll
